/*
 * Firecracker API
 *
 * RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: compute-capsule@amazon.com
 * Generated by: https://openapi-generator.tech
 */

/// EntropyDevice : Defines an entropy device.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntropyDevice {
    #[serde(rename = "rate_limiter", skip_serializing_if = "Option::is_none")]
    pub rate_limiter: Option<Box<crate::models::RateLimiter>>,
}

impl EntropyDevice {
    /// Defines an entropy device.
    pub fn new() -> EntropyDevice {
        EntropyDevice {
            rate_limiter: None,
        }
    }
}


